### ISSUE TITLE
[BUG]索引没有滚动创建

### ISSUE THREAD

**Issue by wqj97** [TencentBlueKing/bk-monitor#1401]
Trace日志从3月18日早上8:00开始不再更新
![image](https://github.com/TencentBlueKing/bk-monitor/assets/18662395/33efac24-4dce-4387-87ff-7beab5536522)

**What happened**:
![img_v3_0293_96f5804a-d1a3-418b-bcbc-c69575cf261g](https://github.com/TencentBlueKing/bk-monitor/assets/18662395/340d2dfa-b5de-4f2a-bb36-bc5be25f839a)
APM更新索引失败

![image](https://github.com/TencentBlueKing/bk-monitor/assets/18662395/277e0652-fd80-4162-b73f-dde301659d1c)
告警事件不再更新

**What you expected to happen**:
正常查询
**How to reproduce it (as minimally and precisely as possible)**:
每次点击启动/修改apm都可以复现
![image](https://github.com/TencentBlueKing/bk-monitor/assets/18662395/f23379cf-c507-400d-90df-f545cea6ac8b)

**Anything else we need to know?**:
![image](https://github.com/TencentBlueKing/bk-monitor/assets/18662395/7037c518-b085-419f-80bb-726c9a3b9c15)

**Comment by liuwenping** [comment]
ES集群未正常初始化导致。可参照“日志平台->配置 ElasticSearch”章节操作一下
https://bk.tencent.com/docs/markdown/ZH/DeploymentGuides/7.1/install-co-suite.md

**Comment by wqj97** [comment]
> ES集群未正常初始化导致。可参照“日志平台->配置 ElasticSearch”章节操作一下 https://bk.tencent.com/docs/markdown/ZH/DeploymentGuides/7.1/install-co-suite.md

之前是好的, 最近才不行, 是需要重新做一次ES集群初始化么? 看提示像是索引轮转周期未执行

**Comment by wqj97** [comment]
> ES集群未正常初始化导致。可参照“日志平台->配置 ElasticSearch”章节操作一下 https://bk.tencent.com/docs/markdown/ZH/DeploymentGuides/7.1/install-co-suite.md

找到问题了, 确实是write索引自动创建导致的
之前没问题是因为trace数据了不大, 刚好没冲突
